### ISSUE TITLE
Subtask: Created Endpoint for Sp3 Salmon Run Statistics

### ISSUE THREAD

**Issue by Voroniyx** [AcronixBot/api-server#2]
- Sub Task zu: https://github.com/AcronixBot/web-s3/issues/2

### Endpunkte: 
- [ ] Complete Overview
- [ ] Maps,
- [ ] Bosses
- [ ] and EggstraWork and BigRun
- [ ] Specific HighScore for a map
- [ ] Highscore for Map in Current Rotation
